import streamlit as st
import requests

import pandas as pd
from io import BytesIO
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
 
import time
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

from modules.financial_analysis import *
from modules.ai_advisor import generate_financial_advice,finance_chatbot_response
from modules.visualization import *
from utils.utils import *
 
from config import APP_TITLE, db
from firebase_admin import auth

import random
from datetime import datetime, timezone


def get_daily_thought():
    thoughts = [
        "Do not save what is left after spending, spend what is left after saving.",
        "A budget is telling your money where to go instead of wondering where it went.",
        "Financial freedom is available to those who learn about it and work for it.",
        "Small savings today create big wealth tomorrow.",
        "Avoid debt that does not create value.",
        "Invest early, even if the amount is small.",
        "Your lifestyle should not grow faster than your income.",
        "Consistency beats intensity in financial growth.",
        "An emergency fund is your financial shield.",
        "Wealth is built through discipline, not luck."
    ]

    # stable random per day
    today = datetime.now().toordinal()
    return thoughts[today % len(thoughts)]
# ---------------- CONFIG ---------------- #
FIREBASE_API_KEY = st.secrets["FIREBASE_API_KEY"]

st.set_page_config(
    page_title=APP_TITLE,
    layout="wide",
    initial_sidebar_state="expanded"
)


# ---------------- SESSION ---------------- #
if "auth_loading" not in st.session_state:
    st.session_state.auth_loading = False
if "analyze_loading" not in st.session_state:
    st.session_state.analyze_loading = False

if "user" not in st.session_state:
    st.session_state.user = None

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "selected_record" not in st.session_state:
    st.session_state.selected_record = None
if "last_ai_call" not in st.session_state:
    st.session_state.last_ai_call = 0


# ---------------- PDF ---------------- #



def generate_pdf(profile, metrics, sections):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()
    content = []

    # ---------- HEADER ---------- #
    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    content.append(Paragraph("FinAIzer Fintech Ltd.", title_style))
    content.append(Spacer(1, 10))
    content.append(Paragraph("Financial Analysis Report", styles["Heading2"]))
    content.append(Spacer(1, 20))

    # ---------- USER INFO ---------- #
    content.append(Paragraph("User Information", styles["Heading3"]))
    content.append(Paragraph(f"Name: {profile['name']}", styles["Normal"]))
    content.append(Paragraph(f"Risk Profile: {profile['risk']}", styles["Normal"]))
    content.append(Paragraph(f"Financial Goal: {profile['goal']}", styles["Normal"]))
    content.append(Spacer(1, 20))

    # ---------- FINANCIAL SUMMARY TABLE ---------- #
    content.append(Paragraph("Financial Summary", styles["Heading3"]))

    table_data = [["Metric", "Value"]]
    for k, v in metrics.items():
        table_data.append([k, v])

    table = Table(table_data, colWidths=[200, 200])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
    ]))

    content.append(table)
    content.append(Spacer(1, 20))

    # ---------- AI INSIGHTS ---------- #
    content.append(Paragraph("AI Financial Insights", styles["Heading3"]))

    for section, text in sections.items():
        content.append(Paragraph(f"<b>{section}</b>", styles["Normal"]))
        content.append(Spacer(1, 5))
        content.append(Paragraph(text, styles["Normal"]))
        content.append(Spacer(1, 12))

    # ---------- FOOTER ---------- #
    content.append(Spacer(1, 20))
    content.append(Paragraph(
        "Generated by FinAIzer AI Financial Advisor",
        styles["Italic"]
    ))

    doc.build(content)
    buffer.seek(0)

    return buffer


# ---------------- AUTH ---------------- #
def signup(email, password):
    try:
        user = auth.create_user(email=email, password=password)
        return user.uid, None
    except Exception as e:
        return None, str(e)


def login(email, password):
    url = f"https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={FIREBASE_API_KEY}"
    payload = {"email": email, "password": password, "returnSecureToken": True}
    res = requests.post(url, json=payload).json()

    if "idToken" in res:
        return res["localId"], None
    return None, res.get("error", {}).get("message", "Login failed")


def logout():
    st.session_state.user = None


# ---------------- SIDEBAR AUTH ---------------- #
# ---------------- SIDEBAR AUTH ---------------- #
st.sidebar.title("FinAIzer")

if not st.session_state.user:
    mode = st.sidebar.radio("Mode", ["Login", "Signup"])
    email = st.sidebar.text_input("Email")
    password = st.sidebar.text_input("Password", type="password")

    if mode == "Signup":
        signup_clicked = st.sidebar.button(
            "Create Account",
            disabled=st.session_state.auth_loading
        )

        if signup_clicked:
            st.session_state.auth_loading = True

            uid, err = signup(email, password)

            if uid:
                st.session_state.user = uid
                st.sidebar.success("Account created and logged in")
                st.session_state.auth_loading = False
                st.rerun()
            else:
                st.sidebar.error(err)
                st.session_state.auth_loading = False

    else:
        login_clicked = st.sidebar.button(
            "Login",
            disabled=st.session_state.auth_loading
        )

        if login_clicked:
            st.session_state.auth_loading = True

            uid, err = login(email, password)

            if uid:
                st.session_state.user = uid
                st.session_state.auth_loading = False
                st.rerun()
            else:
                st.sidebar.error(err)
                st.session_state.auth_loading = False

else:
    st.sidebar.success("Logged in")
    if st.sidebar.button("Logout"):
        logout()
        st.rerun()


if not st.session_state.user:
    st.title("FinAIzer | Login required")
    st.stop()


# ---------------- PROFILE ---------------- #
user_ref = db.collection("users").document(st.session_state.user)
profile_doc = user_ref.get()

if not profile_doc.exists:
    st.title("Profile Setup")

    name = st.text_input("Name")
    age_group = st.selectbox("Age Group", ["18-25", "25-35", "35-50", "50+"])
    risk = st.selectbox("Risk Appetite", ["Low", "Medium", "High"])
    goal = st.text_input("Primary Financial Goal")

    if st.button("Save Profile"):
        user_ref.set({
            "name": name,
            "age_group": age_group,
            "risk": risk,
            "goal": goal,
            "created_at": datetime.now(timezone.now)
        })
        st.rerun()

    st.stop()

profile = profile_doc.to_dict()


# ---------------- UI ---------------- #
 

# Greeting logic
hour = datetime.now().hour

if hour < 12:
    greeting = "Good Morning"
elif hour < 17:
    greeting = "Good Afternoon"
else:
    greeting = "Good Evening"

st.title(f"{greeting}, {profile['name']}")

st.caption(f"Risk: {profile['risk']} | Goal: {profile['goal']}")

# Thought of the day
st.markdown("### Financial Thought of the Day")
st.info(get_daily_thought())

# ---------------- INPUT ---------------- #
st.sidebar.header("Financial Input")

prefill = st.session_state.selected_record or {}

income = st.sidebar.number_input("Monthly Income", min_value=0, value=int(prefill.get("income", 0)))
expenses = st.sidebar.number_input("Monthly Expenses", min_value=0, value=int(prefill.get("expenses", 0)))
savings = st.sidebar.number_input("Current Savings", min_value=0, value=int(prefill.get("savings", 0)))
debt = st.sidebar.number_input("Outstanding Debt", min_value=0, value=int(prefill.get("debt", 0)))

analyze_clicked = st.sidebar.button("Analyze", disabled=st.session_state.analyze_loading)


# ---------------- MAIN GRID ---------------- #
col_main, col_side = st.columns([3, 1])


with col_main:

    if analyze_clicked:
        st.session_state.analyze_loading = True

        # -------- RATE LIMIT -------- #
        try:
            now = time.time()
            if now - st.session_state.last_ai_call < 3:
                st.warning("Please wait before running analysis again.")
                st.stop()

            st.session_state.last_ai_call = now

            if income <= 0 or expenses <= 0:
                st.warning("Enter valid values")
            else:
                savings_r = savings_ratio(income, savings)
                debt_r = debt_ratio(income, debt)
                invest = investment_potential(income, expenses)
                emergency = emergency_fund_required(expenses)
                score = financial_health_score(savings_r, debt_r)

                user_ref.collection("data").add({
                    "income": income,
                    "expenses": expenses,
                    "savings": savings,
                    "debt": debt,
                    "timestamp": datetime.now(timezone.utc)
                })

                # -------- INTELLIGENCE LAYER -------- #
                if expenses > income:
                    st.error("Spending exceeds income. Immediate correction needed.")

                if debt_r > 40:
                    st.warning("High debt ratio detected. Consider reducing liabilities.")

                if savings_r < 10:
                    st.warning("Savings rate is low. Increase savings for stability.")

                if savings_r > 30:
                    st.success("Strong savings discipline. Good financial behavior.")

                # -------- EXISTING UI -------- #
                st.subheader("Overview")

                m1, m2, m3, m4 = st.columns(4)
                m1.metric("Savings Ratio", f"{savings_r:.2f}%")
                m2.metric("Debt Ratio", f"{debt_r:.2f}%")
                m3.metric("Investment Potential", f"{invest:,.0f}")
                m4.metric("Emergency Fund", f"{emergency:,.0f}")

                st.metric("Financial Score", f"{score}/100")

                st.subheader("Analytics")

                c1, c2 = st.columns(2)
                with c1:
                    st.pyplot(income_allocation_pie(income, expenses, savings))
                with c2:
                    st.pyplot(savings_bar_chart(savings))

                st.plotly_chart(financial_health_gauge(score), use_container_width=True)

                st.subheader("AI Insights")

                data = {
                    "income": income,
                    "expenses": expenses,
                    "savings": savings,
                    "debt": debt,
                    "savings_ratio": savings_r,
                    "debt_ratio": debt_r,
                    "user_name": profile["name"],
                    "risk": profile["risk"],
                    "goal": profile["goal"]
                }

                try:
                    advice = generate_financial_advice(data)
                except Exception:
                    st.error("AI service unavailable. Try again later.")
                    advice = ""
                sections = parse_advice(advice)
                if not any(v.strip() for v in sections.values()):
                    st.error("AI response format issue. Retrying...")
                    advice = generate_financial_advice(data)
                    sections = parse_advice(advice)
                for k, v in sections.items():
                    st.write(k)
                    st.info(v)

                # -------- PDF -------- #
                metrics = {
                    "Savings Ratio": f"{savings_r:.2f}%",
                    "Debt Ratio": f"{debt_r:.2f}%",
                    "Score": f"{score}"
                }

                pdf_buffer = generate_pdf(profile, metrics, sections)

                st.download_button(
                    label="Download PDF Report",
                    data=pdf_buffer,
                    file_name="FinAIzer_Report.pdf",
                    mime="application/pdf"
                )
                st.session_state.analyze_loading = False
        except Exception as e:
            st.error(f"Error: {str(e)}")

        finally:
            st.session_state.analyze_loading = False


# ---------------- SIDE PANEL ---------------- #
# ---------------- HISTORY (FULL WIDTH) ---------------- #
st.markdown("---")
st.subheader("History")

docs = user_ref.collection("data")\
    .order_by("timestamp", direction="DESCENDING")\
    .limit(20).stream()

records = []
for doc in docs:
    d = doc.to_dict()
    d["id"] = doc.id
    records.append(d)

if records:
    df = pd.DataFrame(records)

    # -------- BIG TABLE -------- #
    st.dataframe(
        df,
        use_container_width=True,
        height=400  # makes it visually strong
    )

    # -------- INTERACTION -------- #
    col1, col2 = st.columns([2, 1])

    with col1:
        selected_id = st.selectbox(
            "Select record to reuse",
            options=[r["id"] for r in records]
        )

    with col2:
        if st.button("Load Record"):
            selected = next(r for r in records if r["id"] == selected_id)
            st.session_state.selected_record = selected
            st.rerun()

else:
    st.info("No records yet. Run an analysis to get started.")


# ---------------- CHAT ---------------- #
st.markdown("---")
st.subheader("Assistant")

user_input = st.chat_input("Ask a financial question")

if user_input:
    try:
        reply = finance_chatbot_response(user_input, profile)
    except Exception:
        reply = "AI is temporarily unavailable."
 
    st.session_state.chat_history.append(("user", user_input))
    st.session_state.chat_history.append(("ai", reply))

for role, msg in st.session_state.chat_history:
    st.chat_message("user" if role == "user" else "assistant").markdown(msg)
